# frozen_string_literal: true

module DhanHQ
  # Strategy framework for building and backtesting trading strategies.
  #
  # Provides a DSL for defining entry/exit rules, risk management,
  # and signal generation.
  #
  # @example Define a simple strategy
  #   class MyStrategy < DhanHQ::Strategy::Base
  #     entry_rule :golden_cross do |data|
  #       data.sma(20).last > data.sma(50).last &&
  #         data.sma(20).last(2) <= data.sma(50).last(2)
  #     end
  #
  #     exit_rule :death_cross do |data|
  #       data.sma(20).last < data.sma(50).last
  #     end
  #   end
  #
  module Strategy
    # Signal represents a trading signal generated by a strategy.
    #
    # @attr_reader [Symbol] type Signal type (:buy, :sell, :hold)
    # @attr_reader [Float] strength Signal strength (0.0 to 1.0)
    # @attr_reader [Hash] metadata Additional signal metadata
    Signal = Struct.new(:type, :strength, :metadata) do
      def buy?
        type == :buy
      end

      def sell?
        type == :sell
      end

      def hold?
        type == :hold
      end

      def to_prompt
        parts = ["signal=#{type}", "strength=#{strength}"]
        parts << "reason=#{metadata[:reason]}" if metadata[:reason]
        parts.join(", ")
      end
    end

    # Base class for all strategies.
    #
    # Provides DSL for defining entry/exit rules and risk management.
    class Base
      attr_reader :name, :params, :position

      def initialize(name: self.class.name, params: {})
        @name = name
        @params = params
        @position = nil
        @entry_rules = {}
        @exit_rules = {}
        @risk_rules = {}
        @signals = []
      end

      # Define an entry rule.
      #
      # @param name [Symbol] Rule name
      # @param priority [Integer] Rule priority (lower = higher priority)
      # @param block [Proc] Rule condition block
      def self.entry_rule(name, priority: 10, &block)
        @entry_rules ||= {}
        @entry_rules[name] = { priority: priority, block: block }
      end

      # Define an exit rule.
      #
      # @param name [Symbol] Rule name
      # @param priority [Integer] Rule priority (lower = higher priority)
      # @param block [Proc] Rule condition block
      def self.exit_rule(name, priority: 10, &block)
        @exit_rules ||= {}
        @exit_rules[name] = { priority: priority, block: block }
      end

      # Define a risk rule.
      #
      # @param name [Symbol] Rule name
      # @param block [Proc] Risk check block
      def self.risk_rule(name, &block)
        @risk_rules ||= {}
        @risk_rules[name] = block
      end

      # Get all entry rules for this strategy class.
      def self.entry_rules
        @entry_rules || {}
      end

      # Get all exit rules for this strategy class.
      def self.exit_rules
        @exit_rules || {}
      end

      # Get all risk rules for this strategy class.
      def self.risk_rules
        @risk_rules || {}
      end

      # Evaluate entry rules against market data.
      #
      # @param data [DhanHQ::MarketData::OHLCSeries] Market data series
      # @return [DhanHQ::Strategy::Signal] Generated signal
      def evaluate_entry(data)
        sorted_rules = self.class.entry_rules.sort_by { |_, v| v[:priority] }

        sorted_rules.each do |rule_name, rule|
          result = rule[:block].call(data, params)
          next unless result

          signal = Signal.new(
            type: :buy,
            strength: calculate_strength(result),
            metadata: { rule: rule_name, data: data }
          )
          @signals << signal
          return signal
        end

        Signal.new(type: :hold, strength: 0.0, metadata: { reason: :no_entry_signal })
      end

      # Evaluate exit rules against market data.
      #
      # @param data [DhanHQ::MarketData::OHLCSeries] Market data series
      # @return [DhanHQ::Strategy::Signal] Generated signal
      def evaluate_exit(data)
        sorted_rules = self.class.exit_rules.sort_by { |_, v| v[:priority] }

        sorted_rules.each do |rule_name, rule|
          result = rule[:block].call(data, params)
          next unless result

          signal = Signal.new(
            type: :sell,
            strength: calculate_strength(result),
            metadata: { rule: rule_name, data: data }
          )
          @signals << signal
          return signal
        end

        Signal.new(type: :hold, strength: 0.0, metadata: { reason: :no_exit_signal })
      end

      # Check all risk rules.
      #
      # @param context [Hash] Risk check context
      # @return [Array<Symbol>] List of violated rule names
      def check_risks(context)
        violations = []

        self.class.risk_rules.each do |rule_name, block|
          result = block.call(context, params)
          violations << rule_name unless result
        end

        violations
      end

      # Get all signals generated by this strategy.
      def signals
        @signals.dup
      end

      # Get the last signal.
      def last_signal
        @signals.last
      end

      private

      def calculate_strength(result)
        case result
        when true then 1.0
        when Numeric then result.clamp(0.0, 1.0)
        else 0.5
        end
      end
    end
  end
end
