# frozen_string_literal: true

module DhanHQ
  module Models
    ##
    # Model wrapper for electronic DIS (Delivery Instruction Slip) flows.
    #
    # To sell holding stocks, one needs to complete the CDSL eDIS flow:
    # 1. Generate T-PIN using {tpin}
    # 2. Retrieve escaped HTML form using {form} and enter T-PIN to mark stock for EDIS approval
    # 3. Check status using {inquire} to verify if stock is approved and marked for sell action
    #
    # You can get ISIN (International Securities Identification Number) of portfolio stocks
    # from the holdings API response.
    #
    # @example Generate T-PIN
    #   response = DhanHQ::Models::Edis.tpin
    #   # Returns 202 Accepted status
    #
    # @example Generate eDIS form for a single stock
    #   response = DhanHQ::Models::Edis.form(
    #     isin: "INE733E01010",
    #     qty: 1,
    #     exchange: "NSE",
    #     segment: "EQ",
    #     bulk: false
    #   )
    #   # => {
    #   #   dhan_client_id: "1000000401",
    #   #   edis_form_html: "<!DOCTYPE html>..."
    #   # }
    #
    # @example Check EDIS status for an ISIN
    #   status = DhanHQ::Models::Edis.inquire("INE00IN01015")
    #   # => {
    #   #   client_id: "1000000401",
    #   #   isin: "INE00IN01015",
    #   #   total_qty: "10",
    #   #   aprvd_qty: "4",
    #   #   status: "SUCCESS",
    #   #   remarks: "eDIS transaction done successfully"
    #   # }
    #
    class Edis < BaseModel
      # Base path backing the model operations.
      HTTP_PATH = "/v2/edis"

      class << self
        ##
        # Shared resource client used by the model helpers.
        #
        # @return [DhanHQ::Resources::Edis] The EDIS resource client instance
        def resource
          @resource ||= DhanHQ::Resources::Edis.new
        end

        ##
        # Retrieves escaped HTML form of CDSL and enters T-PIN to mark the stock for EDIS approval.
        #
        # User has to render this form at their end to unescape. The form contains hidden fields
        # that will automatically submit to CDSL's eDIS verification endpoint.
        #
        # @param params [Hash{Symbol => String, Integer, Boolean}] The EDIS form request parameters
        #   @option params [String] :isin (required) International Securities Identification Number
        #     (12-digit alphanumeric code). You can get ISIN from the holdings API response.
        #   @option params [Integer] :qty (required) Number of shares to mark for EDIS transaction
        #   @option params [String] :exchange (required) Exchange identifier. Must be either "NSE" or "BSE"
        #   @option params [String] :segment (required) Segment identifier. Must be "EQ"
        #   @option params [Boolean] :bulk (optional, default: false) Set to true to mark EDIS for
        #     all stocks in portfolio. When true, other parameters may be ignored.
        #
        # @return [Hash{Symbol => String}] The EDIS form response containing escaped HTML form.
        #   Response keys are normalized to snake_case:
        #   - **:dhan_client_id** [String] User-specific identification generated by Dhan
        #   - **:edis_form_html** [String] Escaped HTML form that needs to be rendered and unescaped
        #
        # @example Generate form for a single stock
        #   response = DhanHQ::Models::Edis.form(
        #     isin: "INE733E01010",
        #     qty: 1,
        #     exchange: "NSE",
        #     segment: "EQ",
        #     bulk: false
        #   )
        #   html_form = response[:edis_form_html]
        #   # Render and unescape the HTML form to complete EDIS approval
        #
        # @example Generate form for bulk EDIS
        #   response = DhanHQ::Models::Edis.form(
        #     isin: "",
        #     qty: 0,
        #     exchange: "NSE",
        #     segment: "EQ",
        #     bulk: true
        #   )
        def form(params)
          resource.form(params)
        end

        ##
        # Submits a bulk EDIS form request for multiple stocks.
        #
        # This is an alternative to using {form} with `bulk: true`. The exact parameter
        # structure may differ from the single form request.
        #
        # @param params [Hash{Symbol => String, Integer, Boolean}] The bulk EDIS form request parameters
        #   @option params [String] :isin (optional) International Securities Identification Number.
        #     May be ignored for bulk requests
        #   @option params [Integer] :qty (optional) Number of shares. May be ignored for bulk requests
        #   @option params [String] :exchange (required) Exchange identifier ("NSE" or "BSE")
        #   @option params [String] :segment (required) Segment identifier ("EQ")
        #   @option params [Boolean] :bulk (optional, default: true) Set to true for bulk operations
        #
        # @return [Hash{Symbol => String}] The bulk EDIS form response containing escaped HTML form.
        #   Response keys are normalized to snake_case:
        #   - **:dhan_client_id** [String] User-specific identification generated by Dhan
        #   - **:edis_form_html** [String] Escaped HTML form that needs to be rendered and unescaped
        #
        # @example Bulk EDIS form request
        #   response = DhanHQ::Models::Edis.bulk_form(
        #     exchange: "NSE",
        #     segment: "EQ",
        #     bulk: true
        #   )
        def bulk_form(params)
          resource.bulk_form(params)
        end

        ##
        # Generates a T-PIN (Transaction PIN) for the configured client.
        #
        # T-PIN is sent to the user's registered mobile number. This T-PIN is required
        # when submitting the EDIS form to mark stocks for sell action.
        #
        # @return [Hash{Symbol => String}] The T-PIN generation response. The T-PIN itself is sent
        #   to the registered mobile number and not returned in the response. Response typically
        #   contains a status indicating successful generation (e.g., "202 Accepted").
        #
        # @example Generate T-PIN
        #   response = DhanHQ::Models::Edis.tpin
        #   # T-PIN will be sent to registered mobile number
        #   # Check your mobile for the T-PIN before submitting the EDIS form
        #
        # @note This is a GET request with no body parameters required
        def tpin
          resource.tpin
        end

        ##
        # Inquires the EDIS status for a specific ISIN to check if stock is approved and marked for sell action.
        #
        # You can check whether a stock has been approved through the EDIS process and is ready
        # for sell action. Alternatively, you can pass "ALL" instead of an ISIN to get EDIS status
        # of all holdings in your portfolio.
        #
        # @param isin [String] International Securities Identification Number (12-digit alphanumeric code).
        #   You can get ISIN from the holdings API response. Alternatively, pass "ALL" to get status
        #   for all holdings in your portfolio.
        #
        # @return [Hash{Symbol => String}] The EDIS inquiry response containing status information.
        #   Response keys are normalized to snake_case:
        #   - **:client_id** [String] User-specific identification
        #   - **:isin** [String] International Securities Identification Number that was queried
        #   - **:total_qty** [String] Total number of shares for the given stock
        #   - **:aprvd_qty** [String] Number of approved stocks that are marked for EDIS
        #   - **:status** [String] Status of the EDIS order (e.g., "SUCCESS", "PENDING", "FAILED")
        #   - **:remarks** [String] Remarks about the order status (e.g., "eDIS transaction done successfully")
        #
        # @example Check status for a specific ISIN
        #   status = DhanHQ::Models::Edis.inquire("INE00IN01015")
        #   puts status[:status]       # => "SUCCESS"
        #   puts status[:aprvd_qty]    # => "4"
        #   puts status[:total_qty]     # => "10"
        #
        # @example Check status for all holdings
        #   all_status = DhanHQ::Models::Edis.inquire("ALL")
        #   # Returns status for all holdings in portfolio
        #
        # @note This is a GET request with no body parameters. The ISIN is passed in the URL path.
        def inquire(isin)
          resource.inquire(isin)
        end
      end

      ##
      # EDIS payloads are validated upstream so no contract is applied.
      #
      # @return [nil] No validation contract is needed for EDIS operations
      def validation_contract
        nil
      end
    end
  end
end
