# frozen_string_literal: true

module DhanHQ
  module Models
    ##
    # Model for creating and managing Forever Orders (also known as Good Till Triggered or GTT orders).
    #
    # Forever Orders are conditional orders that remain active until triggered, modified, or cancelled.
    # They can be configured as:
    # - **SINGLE**: A single order that triggers when the trigger price is reached
    # - **OCO** (One-Cancels-Other): Two linked orders where execution of one cancels the other
    #
    # Order placement, modification, and cancellation APIs require Static IP whitelisting.
    #
    # @example Create a single forever order
    #   order = DhanHQ::Models::ForeverOrder.create(
    #     order_flag: "SINGLE",
    #     transaction_type: "BUY",
    #     exchange_segment: "NSE_EQ",
    #     product_type: "CNC",
    #     order_type: "LIMIT",
    #     validity: "DAY",
    #     security_id: "1333",
    #     quantity: 5,
    #     price: 1428.0,
    #     trigger_price: 1427.0
    #   )
    #
    # @example Create an OCO forever order
    #   order = DhanHQ::Models::ForeverOrder.create(
    #     order_flag: "OCO",
    #     transaction_type: "BUY",
    #     exchange_segment: "NSE_EQ",
    #     product_type: "CNC",
    #     order_type: "LIMIT",
    #     validity: "DAY",
    #     security_id: "1333",
    #     quantity: 5,
    #     price: 1428.0,
    #     trigger_price: 1427.0,
    #     price1: 1420.0,
    #     trigger_price1: 1419.0,
    #     quantity1: 10
    #   )
    #
    # @example Modify a forever order
    #   order = DhanHQ::Models::ForeverOrder.find("5132208051112")
    #   order.modify(
    #     order_flag: "SINGLE",
    #     order_type: "LIMIT",
    #     leg_name: "TARGET_LEG",
    #     quantity: 15,
    #     price: 1421.0,
    #     trigger_price: 1420.0,
    #     validity: "DAY"
    #   )
    #
    # @example Cancel a forever order
    #   order = DhanHQ::Models::ForeverOrder.find("5132208051112")
    #   order.cancel  # => true
    #
    # @example List all forever orders
    #   orders = DhanHQ::Models::ForeverOrder.all
    #   orders.each { |order| puts order.order_status }
    #
    class ForeverOrder < BaseModel
      attributes :dhan_client_id, :order_id, :correlation_id, :order_status,
                 :transaction_type, :exchange_segment, :product_type, :order_flag,
                 :order_type, :validity, :trading_symbol, :security_id, :quantity,
                 :disclosed_quantity, :price, :trigger_price, :price1,
                 :trigger_price1, :quantity1, :leg_name, :create_time,
                 :update_time, :exchange_time, :drv_expiry_date, :drv_option_type,
                 :drv_strike_price

      class << self
        ##
        # Provides a shared instance of the ForeverOrders resource.
        #
        # @return [DhanHQ::Resources::ForeverOrders] The ForeverOrders resource client instance
        def resource
          @resource ||= DhanHQ::Resources::ForeverOrders.new
        end

        ##
        # Retrieves an array of all existing Forever Orders in the account.
        #
        # @return [Array<ForeverOrder>] Array of ForeverOrder objects. Returns empty array if no orders exist.
        #   Each ForeverOrder object contains (keys normalized to snake_case):
        #   - **:dhan_client_id** [String] User-specific identification generated by Dhan
        #   - **:order_id** [String] Order-specific identification generated by Dhan
        #   - **:order_status** [String] Last updated status of the order.
        #     Valid values: "TRANSIT", "PENDING", "REJECTED", "CANCELLED", "TRADED", "EXPIRED", "CONFIRM"
        #   - **:transaction_type** [String] The trading side of transaction. Valid values: "BUY", "SELL"
        #   - **:exchange_segment** [String] Exchange and segment. Valid values: "NSE_EQ", "NSE_FNO", "BSE_EQ", "MCX_COMM"
        #   - **:product_type** [String] Product type of trade. Valid values: "CNC", "INTRADAY", "MARGIN", "CO", "BO"
        #   - **:order_type** [String] Order type. Valid values: "SINGLE", "OCO"
        #   - **:trading_symbol** [String] Symbol of the instrument in which forever order is placed
        #   - **:security_id** [String] Exchange standard ID for each scrip
        #   - **:quantity** [Integer] Number of shares for the order
        #   - **:price** [Float] Price at which order is placed
        #   - **:trigger_price** [Float] Price at which order is to be triggered
        #   - **:leg_name** [String] Order leg of Forever Order.
        #     Valid values: "TARGET_LEG" (for Single and First leg of OCO), "STOP_LOSS_LEG" (for Second leg of OCO)
        #   - **:create_time** [String] Time at which the Forever Order is created
        #   - **:update_time** [String, nil] Time at which the Forever Order is updated
        #   - **:exchange_time** [String, nil] Time at which order reached at exchange end
        #   - **:drv_expiry_date** [String, nil] Contract Expiry Date for Derivative contract
        #   - **:drv_option_type** [String, nil] Type of Option. Valid values: "CALL", "PUT"
        #   - **:drv_strike_price** [Float] Strike Price in case of Option Contract
        #
        # @example List all forever orders
        #   orders = DhanHQ::Models::ForeverOrder.all
        #   orders.each do |order|
        #     puts "#{order.order_id}: #{order.order_status} - #{order.trading_symbol}"
        #   end
        def all
          response = resource.all
          return [] unless response.is_a?(Array)

          response.map { |o| new(o, skip_validation: true) }
        end

        ##
        # Retrieves a specific Forever Order by its order ID.
        #
        # @param order_id [String] Order-specific identification generated by Dhan
        # @return [ForeverOrder, nil] ForeverOrder object if found, nil otherwise
        #
        # @example Find a specific forever order
        #   order = DhanHQ::Models::ForeverOrder.find("5132208051112")
        #   if order
        #     puts "Status: #{order.order_status}"
        #     puts "Symbol: #{order.trading_symbol}"
        #   end
        def find(order_id)
          response = resource.find(order_id)
          return nil unless response.is_a?(Hash) && response.any?

          new(response, skip_validation: true)
        end

        ##
        # Creates a new Forever Order (Good Till Triggered order).
        #
        # Forever Orders can be configured as SINGLE (one order) or OCO (One-Cancels-Other with two linked orders).
        # The order remains active until triggered, modified, or cancelled.
        #
        # @param params [Hash{Symbol => String, Integer, Float}] Forever order creation parameters
        #   @option params [String] :dhan_client_id (required) User-specific identification generated by Dhan.
        #     Must be explicitly provided in the params hash
        #   @option params [String] :correlation_id (optional) User/partner generated ID for tracking purposes
        #   @option params [String] :order_flag (required) Order flag type.
        #     Valid values: "OCO" for OCO order, "SINGLE" for Forever Order
        #   @option params [String] :transaction_type (required) The trading side of transaction.
        #     Valid values: "BUY", "SELL"
        #   @option params [String] :exchange_segment (required) Exchange and segment identifier.
        #     Valid values: "NSE_EQ", "NSE_FNO", "BSE_EQ", "BSE_FNO"
        #   @option params [String] :product_type (required) Product type.
        #     Valid values: "CNC", "MTF"
        #   @option params [String] :order_type (required) Order type.
        #     Valid values: "LIMIT", "MARKET"
        #   @option params [String] :validity (required) Validity of order for execution.
        #     Valid values: "DAY", "IOC"
        #   @option params [String] :security_id (required) Exchange standard ID for each scrip
        #   @option params [Integer] :quantity (required) Number of shares for the order
        #   @option params [Integer] :disclosed_quantity (optional) Number of shares visible to market.
        #     Keep more than 30% of quantity
        #   @option params [Float] :price (required) Price at which order is placed
        #   @option params [Float] :trigger_price (required) Price at which order is to be triggered
        #   @option params [Float] :price1 (conditionally required) Target price for OCO order.
        #     Required when order_flag is "OCO"
        #   @option params [Float] :trigger_price1 (conditionally required) Target trigger price for OCO order.
        #     Required when order_flag is "OCO"
        #   @option params [Integer] :quantity1 (conditionally required) Target quantity for OCO order.
        #     Required when order_flag is "OCO"
        #
        # @return [ForeverOrder, nil] ForeverOrder object with order details if creation succeeds, nil otherwise.
        #   Response structure includes:
        #   - **:order_id** [String] Order-specific identification generated by Dhan
        #   - **:order_status** [String] Order status. Valid values: "TRANSIT", "PENDING", "REJECTED",
        #     "CANCELLED", "TRADED", "EXPIRED", "CONFIRM"
        #
        # @example Create a single forever order
        #   order = DhanHQ::Models::ForeverOrder.create(
        #     dhan_client_id: "1000000132",
        #     order_flag: "SINGLE",
        #     transaction_type: "BUY",
        #     exchange_segment: "NSE_EQ",
        #     product_type: "CNC",
        #     order_type: "LIMIT",
        #     validity: "DAY",
        #     security_id: "1333",
        #     quantity: 5,
        #     disclosed_quantity: 1,
        #     price: 1428.0,
        #     trigger_price: 1427.0
        #   )
        #
        # @example Create an OCO forever order
        #   order = DhanHQ::Models::ForeverOrder.create(
        #     dhan_client_id: "1000000132",
        #     order_flag: "OCO",
        #     transaction_type: "BUY",
        #     exchange_segment: "NSE_EQ",
        #     product_type: "CNC",
        #     order_type: "LIMIT",
        #     validity: "DAY",
        #     security_id: "1333",
        #     quantity: 5,
        #     price: 1428.0,
        #     trigger_price: 1427.0,
        #     price1: 1420.0,
        #     trigger_price1: 1419.0,
        #     quantity1: 10
        #   )
        #
        # @note Order placement APIs require Static IP whitelisting
        def create(params)
          response = resource.create(params)
          return nil unless response.is_a?(Hash) && response["orderId"]

          find(response["orderId"])
        end
      end

      ##
      # Modifies an existing Forever Order.
      #
      # The variables that can be modified are: price, quantity, order_type, disclosed_quantity,
      # trigger_price, and validity. For OCO orders, you can specify which leg to modify using leg_name.
      #
      # @param new_params [Hash{Symbol => String, Integer, Float}] Modification parameters
      #   @option new_params [String] :dhan_client_id (required) User-specific identification generated by Dhan.
      #     Must be explicitly provided in the params hash
      #   @option new_params [String] :order_id (required) Order-specific identification generated by Dhan.
      #     Must be explicitly provided in the params hash
      #   @option new_params [String] :order_flag (required) Order flag type.
      #     Valid values: "OCO" for OCO order, "SINGLE" for Forever Order
      #   @option new_params [String] :order_type (required) Order type.
      #     Valid values: "LIMIT", "MARKET", "STOP_LOSS", "STOP_LOSS_MARKET"
      #   @option new_params [String] :leg_name (required) Order leg of Forever Order where modification is to be done.
      #     Valid values: "TARGET_LEG" (for Single and First leg of OCO), "STOP_LOSS_LEG" (for Second leg of OCO)
      #   @option new_params [Integer] :quantity (required) Number of shares for the order
      #   @option new_params [Float] :price (required) Price at which order is placed
      #   @option new_params [Integer] :disclosed_quantity (optional) Number of shares visible to market.
      #     Keep more than 30% of quantity
      #   @option new_params [Float] :trigger_price (required) Price at which order is to be triggered
      #   @option new_params [String] :validity (required) Validity of order for execution.
      #     Valid values: "DAY", "IOC"
      #
      # @return [ForeverOrder, nil] Updated ForeverOrder object if modification succeeds, nil otherwise.
      #   Response structure includes:
      #   - **:order_id** [String] Order-specific identification generated by Dhan
      #   - **:order_status** [String] Last updated status of the order. Valid values: "TRANSIT", "PENDING",
      #     "REJECTED", "CANCELLED", "TRADED", "EXPIRED", "CONFIRM"
      #
      # @example Modify a single forever order
      #   order = DhanHQ::Models::ForeverOrder.find("5132208051112")
      #   order.modify(
      #     dhan_client_id: "1000000132",
      #     order_id: "5132208051112",
      #     order_flag: "SINGLE",
      #     order_type: "LIMIT",
      #     leg_name: "TARGET_LEG",
      #     quantity: 15,
      #     price: 1421.0,
      #     disclosed_quantity: 1,
      #     trigger_price: 1420.0,
      #     validity: "DAY"
      #   )
      #
      # @example Modify the stop loss leg of an OCO order
      #   order.modify(
      #     dhan_client_id: "1000000132",
      #     order_id: "5132208051112",
      #     order_flag: "OCO",
      #     order_type: "LIMIT",
      #     leg_name: "STOP_LOSS_LEG",
      #     quantity: 10,
      #     price: 1400.0,
      #     trigger_price: 1399.0,
      #     validity: "DAY"
      #   )
      #
      # @raise [RuntimeError] If order_id is not available
      # @note Order modification APIs require Static IP whitelisting
      def modify(new_params)
        raise "Order ID is required to modify a forever order" unless order_id

        response = self.class.resource.update(order_id, new_params)
        return self.class.find(order_id) if self.class.send(:success_response?, response)

        nil
      end

      ##
      # Cancels a pending Forever Order using the Order ID.
      #
      # @return [Boolean] true if cancellation succeeds (order_status becomes "CANCELLED"), false otherwise.
      #   Response structure includes:
      #   - **:order_id** [String] Order-specific identification generated by Dhan
      #   - **:order_status** [String] Order status after cancellation. Valid values: "TRANSIT", "PENDING",
      #     "REJECTED", "CANCELLED", "TRADED", "EXPIRED", "CONFIRM"
      #
      # @example Cancel a forever order
      #   order = DhanHQ::Models::ForeverOrder.find("5132208051112")
      #   if order.cancel
      #     puts "Order #{order.order_id} cancelled successfully"
      #   end
      #
      # @raise [RuntimeError] If order_id is not available
      # @note Order cancellation APIs require Static IP whitelisting
      def cancel
        raise "Order ID is required to cancel a forever order" unless order_id

        response = self.class.resource.cancel(order_id)
        response["orderStatus"] == "CANCELLED"
      end
    end
  end
end
