# frozen_string_literal: true

module DhanHQ
  module Models
    ##
    # Model for retrieving trading account fund information including balance, margin utilized, collateral, etc.
    #
    # This endpoint provides comprehensive information about your trading account including available balance,
    # start of day limit, collateral amounts, utilized amounts, and withdrawable balance.
    #
    # @example Fetch complete fund details
    #   funds = DhanHQ::Models::Funds.fetch
    #   puts "Available Balance: #{funds.available_balance}"
    #   puts "Start of Day Limit: #{funds.sod_limit}"
    #   puts "Utilized Amount: #{funds.utilized_amount}"
    #   puts "Withdrawable Balance: #{funds.withdrawable_balance}"
    #
    # @example Fetch only available balance
    #   balance = DhanHQ::Models::Funds.balance
    #   puts "Available to trade: #{balance}"
    #
    # @note The API response contains a typo in the field name (`availabelBalance`). The model automatically
    #   maps this to the correctly spelled `available_balance` attribute for convenience.
    #
    class Funds < BaseModel
      # Base path used by the funds resource.
      HTTP_PATH = "/v2/fundlimit"

      attributes :available_balance, :sod_limit, :collateral_amount, :receiveable_amount, :utilized_amount,
                 :blocked_payout_amount, :withdrawable_balance

      ##
      # Normalizes the typo'd `availabelBalance` key from the API response to `available_balance`.
      #
      # The API currently returns `availabelBalance` (note the typo). This method ensures backwards
      # compatibility while exposing a correctly spelled attribute accessor.
      #
      # @return [void]
      def assign_attributes
        if @attributes.key?(:availabel_balance) && !@attributes.key?(:available_balance)
          @attributes[:available_balance] = @attributes[:availabel_balance]
        end
        super
      end

      class << self
        ##
        # Provides a shared instance of the Funds resource.
        #
        # @return [DhanHQ::Resources::Funds] The Funds resource client instance
        def resource
          @resource ||= DhanHQ::Resources::Funds.new
        end

        ##
        # Fetches all fund limit details for your trading account.
        #
        # Retrieves comprehensive information about account balance, margin utilized, collateral,
        # receivable amounts, and withdrawable balance. No request parameters are required.
        #
        # @return [Funds] Funds object containing all account fund information.
        #   Response structure (keys normalized to snake_case):
        #   - **:dhan_client_id** [String] User-specific identification generated by Dhan
        #   - **:available_balance** [Float] Available amount to trade
        #   - **:sod_limit** [Float] Start of the day balance in account
        #   - **:collateral_amount** [Float] Amount received against collateral
        #   - **:receiveable_amount** [Float] Amount available against selling deliveries
        #   - **:utilized_amount** [Float] Amount utilised in the day
        #   - **:blocked_payout_amount** [Float] Amount blocked against payout request
        #   - **:withdrawable_balance** [Float] Amount available to withdraw in bank account
        #
        # @example Fetch complete fund details
        #   funds = DhanHQ::Models::Funds.fetch
        #   puts "Available Balance: ₹#{funds.available_balance}"
        #   puts "SOD Limit: ₹#{funds.sod_limit}"
        #   puts "Utilized: ₹#{funds.utilized_amount}"
        #   puts "Withdrawable: ₹#{funds.withdrawable_balance}"
        #
        # @example Check if sufficient balance for trading
        #   funds = DhanHQ::Models::Funds.fetch
        #   if funds.available_balance >= 10000.0
        #     puts "Sufficient balance for trading"
        #   else
        #     puts "Low balance: ₹#{funds.available_balance}"
        #   end
        #
        # @note This is a GET request with no body parameters required
        def fetch
          response = resource.fetch
          new(response, skip_validation: true)
        end

        ##
        # Convenience method to fetch only the available balance.
        #
        # This method calls {fetch} internally and returns just the `available_balance` attribute,
        # which is the amount available to trade.
        #
        # @return [Float] Available balance in the trading account (amount available to trade).
        #   Returns 0.0 if unavailable or on error.
        #
        # @example Quick balance check
        #   balance = DhanHQ::Models::Funds.balance
        #   puts "Available to trade: ₹#{balance}"
        #
        # @example Use in conditional logic
        #   if DhanHQ::Models::Funds.balance > 50000
        #     # Proceed with large order
        #   end
        def balance
          fetch.available_balance
        end
      end
    end
  end
end
