# frozen_string_literal: true

module DhanHQ
  module Models
    ##
    # Model for managing the trading kill switch feature.
    #
    # The Kill Switch API lets you activate or deactivate the kill switch for your account,
    # which will disable trading for the current trading day. This is a safety feature that
    # can be used to prevent further trading activity when needed.
    #
    # @note **Important**: Before activating the kill switch, you must ensure that all your
    #   positions are closed and there are no pending orders in your account. The kill switch
    #   will not activate if there are open positions or pending orders.
    #
    # @example Activate kill switch
    #   response = DhanHQ::Models::KillSwitch.activate
    #   puts response[:kill_switch_status]
    #   # => "Kill Switch has been successfully activated"
    #
    # @example Deactivate kill switch
    #   response = DhanHQ::Models::KillSwitch.deactivate
    #   puts response[:kill_switch_status]
    #
    # @example Update kill switch with custom status
    #   response = DhanHQ::Models::KillSwitch.update("ACTIVATE")
    #   if response[:kill_switch_status].include?("successfully")
    #     puts "Kill switch activated"
    #   end
    #
    class KillSwitch < BaseModel
      # Base path used by the kill switch resource.
      HTTP_PATH = "/v2/killswitch"

      class << self
        ##
        # Provides a shared instance of the KillSwitch resource.
        #
        # @return [DhanHQ::Resources::KillSwitch] The KillSwitch resource client instance
        def resource
          @resource ||= DhanHQ::Resources::KillSwitch.new
        end

        ##
        # Updates the kill switch status with the specified action.
        #
        # Allows you to set the kill switch to either "ACTIVATE" or "DEACTIVATE" state.
        # The status is passed as a query parameter to the API endpoint.
        #
        # @param status [String] Kill switch action to perform.
        #   Valid values: "ACTIVATE", "DEACTIVATE"
        #
        # @return [Hash{Symbol => String}] Response hash containing kill switch operation result.
        #   Response structure (keys normalized to snake_case):
        #   - **:dhan_client_id** [String] User-specific identification generated by Dhan
        #   - **:kill_switch_status** [String] Status message indicating the result of the operation.
        #     For activation: "Kill Switch has been successfully activated"
        #     For deactivation: Status message for deactivation
        #
        # @example Update kill switch status
        #   response = DhanHQ::Models::KillSwitch.update("ACTIVATE")
        #   puts response[:kill_switch_status]
        #
        # @example Check if activation was successful
        #   response = DhanHQ::Models::KillSwitch.update("ACTIVATE")
        #   if response[:kill_switch_status].include?("successfully")
        #     puts "Kill switch is now active"
        #   end
        #
        def update(status)
          resource.update(kill_switch_status: status)
        end

        ##
        # Activates the kill switch for your trading account.
        #
        # Disables trading for the current trading day. All trading operations will be blocked
        # until the kill switch is deactivated. This is a safety feature to prevent further
        # trading activity.
        #
        # @note **Prerequisites**: All positions must be closed and there must be no pending
        #   orders in your account before activation. The API will reject the activation request
        #   if these conditions are not met.
        #
        # @return [Hash{Symbol => String}] Response hash containing kill switch activation result.
        #   Response structure (keys normalized to snake_case):
        #   - **:dhan_client_id** [String] User-specific identification generated by Dhan
        #   - **:kill_switch_status** [String] Status message, typically:
        #     "Kill Switch has been successfully activated"
        #
        # @example Activate kill switch
        #   response = DhanHQ::Models::KillSwitch.activate
        #   puts response[:kill_switch_status]
        #   # => "Kill Switch has been successfully activated"
        #
        # @example Activate with error handling
        #   begin
        #     response = DhanHQ::Models::KillSwitch.activate
        #     if response[:kill_switch_status].include?("successfully")
        #       puts "✓ Kill switch activated - trading disabled"
        #     end
        #   rescue => e
        #     puts "Failed to activate kill switch: #{e.message}"
        #     puts "Ensure all positions are closed and no orders are pending"
        #   end
        #
        def activate
          update("ACTIVATE")
        end

        ##
        # Deactivates the kill switch for your trading account.
        #
        # Re-enables trading for your account. After deactivation, you can resume placing
        # orders and executing trades normally.
        #
        # @return [Hash{Symbol => String}] Response hash containing kill switch deactivation result.
        #   Response structure (keys normalized to snake_case):
        #   - **:dhan_client_id** [String] User-specific identification generated by Dhan
        #   - **:kill_switch_status** [String] Status message indicating deactivation result
        #
        # @example Deactivate kill switch
        #   response = DhanHQ::Models::KillSwitch.deactivate
        #   puts response[:kill_switch_status]
        #
        # @example Re-enable trading
        #   response = DhanHQ::Models::KillSwitch.deactivate
        #   if response[:kill_switch_status].include?("successfully")
        #     puts "✓ Trading re-enabled"
        #   end
        #
        def deactivate
          update("DEACTIVATE")
        end
      end

      ##
      # No explicit validation contract is required for kill switch updates.
      #
      # Kill switch operations are simple status updates that don't require complex validation.
      # The API handles validation server-side.
      #
      # @return [nil] Always returns nil as no validation contract is needed
      #
      # @api private
      def validation_contract
        nil
      end
    end
  end
end
