# frozen_string_literal: true

module DhanHQ
  module Models
    ##
    # Model representing a single ledger entry in the Trading Account Ledger Report.
    #
    # The Ledger Report contains all credit and debit transaction details for a particular time interval.
    # Each entry represents a single transaction with details such as narration, voucher information,
    # debit/credit amounts, and running balance.
    #
    # @example Fetch ledger entries for a date range
    #   entries = DhanHQ::Models::LedgerEntry.all(
    #     from_date: "2024-04-01",
    #     to_date: "2024-04-30"
    #   )
    #   entries.each do |entry|
    #     puts "#{entry.voucherdate}: #{entry.narration} - #{entry.debit} / #{entry.credit}"
    #   end
    #
    # @example Calculate total credits and debits
    #   entries = DhanHQ::Models::LedgerEntry.all(
    #     from_date: "2024-04-01",
    #     to_date: "2024-04-30"
    #   )
    #   total_debits = entries.sum { |e| e.debit.to_f }
    #   total_credits = entries.sum { |e| e.credit.to_f }
    #
    class LedgerEntry < BaseModel
      # Base path for ledger endpoint.
      HTTP_PATH = "/v2/ledger"

      attributes :dhan_client_id, :narration, :voucherdate, :exchange,
                 :voucherdesc, :vouchernumber, :debit, :credit, :runbal

      class << self
        ##
        # Provides a shared instance of the Statements resource.
        #
        # @return [DhanHQ::Resources::Statements] The Statements resource client instance
        def resource
          @resource ||= DhanHQ::Resources::Statements.new
        end

        ##
        # Retrieves Trading Account Ledger Report entries for the specified date range.
        #
        # Fetches all credit and debit transaction details for the given time interval.
        # The ledger entries include transaction descriptions, voucher information, amounts,
        # and running balances.
        #
        # @param from_date [String] Start date of the ledger report in YYYY-MM-DD format.
        #   Example: "2024-04-01"
        # @param to_date [String] End date of the ledger report in YYYY-MM-DD format.
        #   Example: "2024-04-30"
        #
        # @return [Array<LedgerEntry>] Array of LedgerEntry objects. Returns empty array if no entries exist.
        #   Each LedgerEntry object contains (keys normalized to snake_case):
        #   - **:dhan_client_id** [String] User-specific identification generated by Dhan
        #   - **:narration** [String] Description of the ledger transaction (e.g., "FUNDS WITHDRAWAL", "CLOSING BALANCE")
        #   - **:voucherdate** [String] Transaction date in format "Mon DD, YYYY" (e.g., "Jun 22, 2022")
        #   - **:exchange** [String] Exchange information for the transaction (e.g., "NSE-CAPITAL", "NSE_CASH")
        #   - **:voucherdesc** [String] Nature of transaction (e.g., "PAYBNK", "CLOSING BALANCE", "OPENING BALANCE")
        #   - **:vouchernumber** [String] System generated transaction number. May be empty string for balance entries
        #   - **:debit** [String] Debit amount as string. Only populated when credit returns "0.00"
        #   - **:credit** [String] Credit amount as string. Only populated when debit returns "0.00"
        #   - **:runbal** [String] Running balance post transaction as string
        #
        # @example Fetch ledger entries for a month
        #   entries = DhanHQ::Models::LedgerEntry.all(
        #     from_date: "2024-04-01",
        #     to_date: "2024-04-30"
        #   )
        #   entries.each do |entry|
        #     puts "#{entry.voucherdate}: #{entry.narration} - Balance: #{entry.runbal}"
        #   end
        #
        # @example Filter entries by transaction type
        #   entries = DhanHQ::Models::LedgerEntry.all(
        #     from_date: "2024-04-01",
        #     to_date: "2024-04-30"
        #   )
        #   withdrawals = entries.select { |e| e.voucherdesc == "PAYBNK" }
        #   puts "Total withdrawals: #{withdrawals.size}"
        #
        # @example Calculate net balance change
        #   entries = DhanHQ::Models::LedgerEntry.all(
        #     from_date: "2024-04-01",
        #     to_date: "2024-04-30"
        #   )
        #   net_change = entries.sum { |e| e.credit.to_f - e.debit.to_f }
        #   puts "Net change: ₹#{net_change}"
        #
        # @note This is a GET request with query parameters. No body required.
        # @note The ledger report represents historical data dumps and entries are returned as-is
        #   without additional validation.
        def all(from_date:, to_date:)
          response = resource.ledger(from_date: from_date, to_date: to_date)

          return [] unless response.is_a?(Array)

          response.map do |entry|
            new(entry, skip_validation: true)
          end
        end
      end

      ##
      # Converts the LedgerEntry model attributes to a hash representation.
      #
      # Useful for serialization, logging, or passing ledger entry data to other methods.
      #
      # @return [Hash{Symbol => String}] Hash representation of the LedgerEntry model containing:
      #   - **:dhan_client_id** [String] User-specific identification
      #   - **:narration** [String] Transaction description
      #   - **:voucherdate** [String] Transaction date
      #   - **:exchange** [String] Exchange information
      #   - **:voucherdesc** [String] Nature of transaction
      #   - **:vouchernumber** [String] Transaction number
      #   - **:debit** [String] Debit amount
      #   - **:credit** [String] Credit amount
      #   - **:runbal** [String] Running balance
      #
      # @example Convert entry to hash
      #   entry = DhanHQ::Models::LedgerEntry.all(
      #     from_date: "2024-04-01",
      #     to_date: "2024-04-30"
      #   ).first
      #   entry_hash = entry.to_h
      #   puts entry_hash[:narration]  # => "FUNDS WITHDRAWAL"
      #   puts entry_hash[:runbal]      # => "957.29"
      #
      def to_h
        {
          dhan_client_id: dhan_client_id,
          narration: narration,
          voucherdate: voucherdate,
          exchange: exchange,
          voucherdesc: voucherdesc,
          vouchernumber: vouchernumber,
          debit: debit,
          credit: credit,
          runbal: runbal
        }
      end
    end
  end
end
