# frozen_string_literal: true

module DhanHQ
  module Models
    ##
    # Model for fetching margin calculation results for orders.
    #
    # The Margin Calculator API provides span margin, exposure margin, VAR (variable margin),
    # brokerage, leverage, and available margin values for any type of order and instrument
    # you want to place. This helps you determine the margin requirements before placing an order.
    #
    # @example Calculate margin for a CNC order
    #   margin = DhanHQ::Models::Margin.calculate(
    #     dhan_client_id: "1000000132",
    #     exchange_segment: "NSE_EQ",
    #     transaction_type: "BUY",
    #     quantity: 5,
    #     product_type: "CNC",
    #     security_id: "1333",
    #     price: 1428.0
    #   )
    #   puts "Total margin required: ₹#{margin.total_margin}"
    #   puts "Available balance: ₹#{margin.available_balance}"
    #
    # @example Calculate margin for stop-loss order
    #   margin = DhanHQ::Models::Margin.calculate(
    #     dhan_client_id: "1000000132",
    #     exchange_segment: "NSE_EQ",
    #     transaction_type: "BUY",
    #     quantity: 10,
    #     product_type: "INTRADAY",
    #     security_id: "1333",
    #     price: 1428.0,
    #     trigger_price: 1427.0
    #   )
    #   puts "Leverage: #{margin.leverage}x"
    #
    # @example Check if sufficient margin is available
    #   margin = DhanHQ::Models::Margin.calculate(params)
    #   if margin.insufficient_balance > 0
    #     puts "Insufficient balance: ₹#{margin.insufficient_balance}"
    #   else
    #     puts "Sufficient margin available"
    #   end
    #
    class Margin < BaseModel
      # Base path used to invoke the calculator.
      HTTP_PATH = "/v2/margincalculator"

      attr_reader :total_margin, :span_margin, :exposure_margin, :available_balance,
                  :variable_margin, :insufficient_balance, :brokerage, :leverage

      class << self
        ##
        # Provides a shared instance of the MarginCalculator resource.
        #
        # @return [DhanHQ::Resources::MarginCalculator] The MarginCalculator resource client instance
        def resource
          @resource ||= DhanHQ::Resources::MarginCalculator.new
        end

        ##
        # Calculates margin requirements for an order before placement.
        #
        # Fetches span margin, exposure margin, VAR (variable margin), brokerage, leverage,
        # and available margin values for the specified order parameters. This allows you to
        # check margin requirements and availability before actually placing the order.
        #
        # @param params [Hash{Symbol => String, Integer, Float}] Request parameters for margin calculation
        #   @option params [String] :dhan_client_id (required) User-specific identification generated by Dhan.
        #     Must be explicitly provided in the params hash
        #   @option params [String] :exchange_segment (required) Exchange and segment identifier.
        #     Valid values: "NSE_EQ", "NSE_FNO", "BSE_EQ", "BSE_FNO", "MCX_COMM"
        #   @option params [String] :transaction_type (required) The trading side of transaction.
        #     Valid values: "BUY", "SELL"
        #   @option params [Integer] :quantity (required) Number of shares for the order. Must be greater than 0
        #   @option params [String] :product_type (required) Product type.
        #     Valid values: "CNC", "INTRADAY", "MARGIN", "MTF", "CO", "BO"
        #   @option params [String] :security_id (required) Exchange standard ID for each scrip
        #   @option params [Float] :price (required) Price at which order is placed. Must be greater than 0
        #   @option params [Float] :trigger_price (conditionally required) Price at which the order is triggered.
        #     Required for STOP_LOSS and STOP_LOSS_MARKET order types
        #
        # @return [Margin] Margin object containing margin calculation results.
        #   Response structure (keys normalized to snake_case):
        #   - **:total_margin** [Float] Total margin required for placing the order successfully
        #   - **:span_margin** [Float] SPAN margin required
        #   - **:exposure_margin** [Float] Exposure margin required
        #   - **:available_balance** [Float] Available amount in trading account
        #   - **:variable_margin** [Float] VAR or Variable margin required
        #   - **:insufficient_balance** [Float] Insufficient amount in trading account
        #     (Available Balance - Total Margin). Negative or zero indicates sufficient margin
        #   - **:brokerage** [Float] Brokerage charges for executing the order
        #   - **:leverage** [String] Margin leverage provided for the order as per product type
        #
        # @example Calculate margin for CNC equity order
        #   margin = DhanHQ::Models::Margin.calculate(
        #     dhan_client_id: "1000000132",
        #     exchange_segment: "NSE_EQ",
        #     transaction_type: "BUY",
        #     quantity: 5,
        #     product_type: "CNC",
        #     security_id: "1333",
        #     price: 1428.0
        #   )
        #   puts "Total Margin: ₹#{margin.total_margin}"
        #   puts "Brokerage: ₹#{margin.brokerage}"
        #
        # @example Calculate margin for intraday order
        #   margin = DhanHQ::Models::Margin.calculate(
        #     dhan_client_id: "1000000132",
        #     exchange_segment: "NSE_EQ",
        #     transaction_type: "SELL",
        #     quantity: 10,
        #     product_type: "INTRADAY",
        #     security_id: "1333",
        #     price: 1500.0
        #   )
        #   puts "Leverage: #{margin.leverage}x"
        #   puts "SPAN Margin: ₹#{margin.span_margin}"
        #
        # @example Calculate margin for stop-loss order
        #   margin = DhanHQ::Models::Margin.calculate(
        #     dhan_client_id: "1000000132",
        #     exchange_segment: "NSE_EQ",
        #     transaction_type: "BUY",
        #     quantity: 5,
        #     product_type: "INTRADAY",
        #     security_id: "1333",
        #     price: 1428.0,
        #     trigger_price: 1427.0
        #   )
        #
        # @raise [DhanHQ::ValidationError] If validation fails for any parameter
        def calculate(params)
          formatted_params = camelize_keys(params)
          validate_params!(formatted_params, DhanHQ::Contracts::MarginCalculatorContract)

          response = resource.calculate(formatted_params)
          new(response, skip_validation: true)
        end
      end

      ##
      # Converts the Margin model attributes to a hash representation.
      #
      # Useful for serialization, logging, or passing margin data to other methods.
      #
      # @return [Hash{Symbol => Float, String}] Hash representation of the Margin model containing:
      #   - **:total_margin** [Float] Total margin required
      #   - **:span_margin** [Float] SPAN margin
      #   - **:exposure_margin** [Float] Exposure margin
      #   - **:available_balance** [Float] Available balance
      #   - **:variable_margin** [Float] Variable margin
      #   - **:insufficient_balance** [Float] Insufficient balance amount
      #   - **:brokerage** [Float] Brokerage charges
      #   - **:leverage** [String] Leverage as string
      #
      # @example Convert margin to hash
      #   margin = DhanHQ::Models::Margin.calculate(params)
      #   margin_hash = margin.to_h
      #   puts margin_hash[:total_margin]  # => 2800.00
      #   puts margin_hash[:leverage]       # => "4.00"
      #
      def to_h
        {
          total_margin: total_margin,
          span_margin: span_margin,
          exposure_margin: exposure_margin,
          available_balance: available_balance,
          variable_margin: variable_margin,
          insufficient_balance: insufficient_balance,
          brokerage: brokerage,
          leverage: leverage
        }
      end
    end
  end
end
