# frozen_string_literal: true

module DhanHQ
  module Models
    ##
    # Model for retrieving authenticated user profile and account information.
    #
    # The User Profile API can be used to check the validity of access token and account setup.
    # It is a simple GET request and serves as a great test API to start integration with DhanHQ.
    # The profile contains account-level metadata including token validity, active segments,
    # DDPI status, MTF consent, and Data API subscription status.
    #
    # @example Fetch user profile to verify token validity
    #   profile = DhanHQ::Models::Profile.fetch
    #   if profile
    #     puts "Client ID: #{profile.dhan_client_id}"
    #     puts "Token Valid Until: #{profile.token_validity}"
    #     puts "Active Segments: #{profile.active_segment}"
    #     puts "DDPI: #{profile.ddpi}"
    #     puts "MTF: #{profile.mtf}"
    #     puts "Data Plan: #{profile.data_plan}"
    #   end
    #
    # @example Check account status
    #   profile = DhanHQ::Models::Profile.fetch
    #   if profile
    #     if profile.ddpi == "Active" && profile.mtf == "Active"
    #       puts "Account is fully active"
    #     else
    #       puts "Some features may be inactive"
    #     end
    #   end
    #
    # @example Verify data API subscription
    #   profile = DhanHQ::Models::Profile.fetch
    #   if profile && profile.data_plan == "Active"
    #     puts "Data API subscription is active until: #{profile.data_validity}"
    #   else
    #     puts "Data API subscription is not active"
    #   end
    #
    class Profile < BaseModel
      # Base path for profile retrieval.
      HTTP_PATH = "/v2/profile"

      attributes :dhan_client_id, :token_validity, :active_segment, :ddpi,
                 :mtf, :data_plan, :data_validity

      class << self
        ##
        # Provides a shared instance of the Profile resource.
        #
        # @return [DhanHQ::Resources::Profile] The Profile resource client instance
        def resource
          @resource ||= DhanHQ::Resources::Profile.new
        end

        ##
        # Fetches the authenticated user's profile details and account information.
        #
        # Retrieves account-level metadata including token validity, active segments,
        # DDPI status, MTF consent status, and Data API subscription status. This is a
        # simple GET request that serves as a great test API to verify your access token
        # and account setup before starting integration.
        #
        # @return [Profile, nil] Profile object with account details if fetch succeeds, nil otherwise.
        #   Response structure (keys normalized to snake_case):
        #   - **:dhan_client_id** [String] User-specific identification generated by Dhan
        #   - **:token_validity** [String] Validity date and time for access token.
        #     Format: "DD/MM/YYYY HH:MM" (e.g., "30/03/2025 15:37")
        #   - **:active_segment** [String] All active segments in user account.
        #     Comma-separated list (e.g., "Equity, Derivative, Currency, Commodity")
        #   - **:ddpi** [String] DDPI (Demat Debit Power of Attorney) status of the user.
        #     Valid values: "Active", "Deactive"
        #   - **:mtf** [String] MTF (Margin Trading Facility) consent status of the user.
        #     Valid values: "Active", "Deactive"
        #   - **:data_plan** [String] Data API subscription status.
        #     Valid values: "Active", "Deactive"
        #   - **:data_validity** [String] Validity date and time for Data API Subscription.
        #     Format: "YYYY-MM-DD HH:MM:SS.S" (e.g., "2024-12-05 09:37:52.0")
        #
        # @example Fetch profile to verify integration
        #   profile = DhanHQ::Models::Profile.fetch
        #   if profile
        #     puts "✓ Access token is valid"
        #     puts "✓ Account setup complete"
        #     puts "Client ID: #{profile.dhan_client_id}"
        #   else
        #     puts "✗ Failed to fetch profile - check access token"
        #   end
        #
        # @example Check account features
        #   profile = DhanHQ::Models::Profile.fetch
        #   if profile
        #     puts "Token valid until: #{profile.token_validity}"
        #     puts "Active segments: #{profile.active_segment}"
        #     puts "DDPI: #{profile.ddpi}"
        #     puts "MTF: #{profile.mtf}"
        #     puts "Data Plan: #{profile.data_plan}"
        #     if profile.data_plan == "Active"
        #       puts "Data API valid until: #{profile.data_validity}"
        #     end
        #   end
        #
        # @example Verify account is ready for trading
        #   profile = DhanHQ::Models::Profile.fetch
        #   if profile
        #     ready = profile.ddpi == "Active" && profile.mtf == "Active"
        #     if ready
        #       puts "Account is ready for trading"
        #     else
        #       puts "Account may have restrictions:"
        #       puts "  DDPI: #{profile.ddpi}"
        #       puts "  MTF: #{profile.mtf}"
        #     end
        #   end
        #
        def fetch
          response = resource.fetch
          return nil unless response.is_a?(Hash)

          new(response, skip_validation: true)
        end
      end

      ##
      # Profile responses are informational and not validated locally.
      #
      # Since profile data is read-only account metadata, no validation contract
      # is needed. The API response is trusted as-is.
      #
      # @return [nil] Always returns nil as profiles are read-only and informational
      #
      # @api private
      def validation_contract
        nil
      end
    end
  end
end
